import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "next/font/google";

export const poppins = Poppins({
  weight: ["400","500","600","700"],
  subsets: ["latin"],
  variable: "--poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={`${poppins.variable}`}>
      <body
      >
        {children}
      </body>
    </html>
  );
}
